### ISSUE TITLE
Node networking link is out of date

### ISSUE THREAD

**Issue by hultzj** [zer0glitch/ocpv-ansible-example#3]
Link leads to a 404 error page 

Here is the latest 4.11 link. 4.12 is hasn't been released yet. 

https://docs.openshift.com/container-platform/4.11/virt/virtual_machines/vm_networking/virt-attaching-vm-multiple-networks.html

**Comment by zer0glitch** [comment]
Which page is this an issue on?

**Comment by cjnovak98** [comment]
I know what he's talking about. I'll correct it to add NNCP/NNCE/NNS explanations + what Jon linked (but OCP 4.10)

Thanks @hultzj!

Sauce: https://docs.openshift.com/container-platform/4.10/virt/virtual_machines/vm_networking/virt-attaching-vm-multiple-networks.html

https://docs.openshift.com/container-platform/4.10/virt/node_network/virt-updating-node-network-config.html
